url: "https://andrewm.codes"
permalink: ordinal
timezone: America/New_York

pagination:
  enabled: true

development:
  unpublished: true
  url: "http://localhost:4000"

svg:
  optimize: true

collections:
  posts:
    output: true
  podcasts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: /images/andrewm-codes-twitter-card.png
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "collections"
      permalink: /:collection/:slug/
      backlinks:
        - name: Podcasts
          url: /podcasts
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "collections"
      permalink: /:collection/:slug/
      backlinks:
        - name: Projects
          url: /projects
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:slug/

cloudinary:
  cloud_name: andrewmcodes

plausible:
  domain: andrewm.codes

# Don't wipe Snowpack generated files (frontend & public)
keep_files:
  - __snowpack__
  - android-chrome-192x192.png
  - android-chrome-512x512.png
  - apple-touch-icon.png
  - favicon-16x16.png
  - favicon-32x32.png
  - favicon.ico
  - robots.txt
  - site.webmanifest
  - sitemap.xml
  - _bridgetown
