destination: _bridgetown
development:
  url: "http://localhost:8080"
  graphql_endpoint: http://localhost:1337/graphql
url: "https://andrewm.codes"
graphql_endpoint: https://andrewmcodes.herokuapp.com/graphql
lsi: true
permalink: simple
template_engine: erb
timezone: America/New_York

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      image: /images/twitter-card.png

plausible:
  domain: andrewm.codes
